export type Revision=number; export type NonNegativeSafeInteger=number; export type Ratio=number; export type Severity='low'|'medium'|'high'; export type SafeUnappliedReason='ai_text_changed'|'merge_conflict'
export type SafeFailureCode='class_review_not_eligible'|'active_generation_conflict'|'class_review_candidate_conflict'|'class_review_source_invalidated'|'class_review_task_invalidated'|'class_review_projection_too_large'|'class_review_prompt_too_large'|'class_review_prompt_calibration_missing'|'class_review_prompt_contract_drift'|'provider_not_configured'|'provider_auth_failed'|'provider_balance_unavailable'|'provider_rate_limited'|'provider_timeout'|'provider_result_unknown'|'provider_unavailable'|'provider_content_filtered'|'provider_unexpected_tool_call'|'provider_invalid_response'
export type ParseErrorCode='not_object'|'missing_key'|'unknown_key'|'invalid_type'|'invalid_value'|'limit_exceeded'|'duplicate_value'|'unknown_reference'; export type ParseResult<T>={ok:true;value:T}|{ok:false;error:{code:ParseErrorCode;path:string}}
export interface SemanticCoverageV1{projectedGroupCount:number;eligibleGroupCount:number;groupCoverage:number;projectedDistinctEssaySupportSum:number;eligibleDistinctEssaySupportSum:number;supportWeightedCoverage:number;projectedOccurrenceSum:number;eligibleOccurrenceSum:number;occurrenceWeightedCoverage:number}
export interface ClassReviewStatisticsV1{totalEssayCount:number;includedEssayCount:number;issueEligibleEssayCount:number;excludedEssayCount:number;issueCoverageRate:number;fullScore:number;scoreSummary:{averageScore:number;highestScore:number;lowestScore:number}|null;scoreBands:Array<{bandId:string;lowerInclusive:number;upperInclusive:number;essayCount:number}>;dimensions:Array<{dimensionId:string;name:string;averageScore:number;maxScore:number;normalizedPerformance:number}>}
export interface AiSummaryV1{overallComment:string;strengths:Array<{title:string;detail:string;dimensionIds:string[]}>;learningRecommendations:Array<{title:string;action:string}>}
export type ClassReviewGenerationCommandV1={contractVersion:'class-review-generation-command-v1';intent:'initial';generationId:string;expectedTaskRevision:number;expectedReportRevision:number|null}|{contractVersion:'class-review-generation-command-v1';intent:'regenerate';generationId:string;expectedTaskRevision:number;expectedReportRevision:number}|{contractVersion:'class-review-generation-command-v1';intent:'apply_candidate';generationId:string;expectedTaskRevision:number;expectedReportRevision:number;expectedGenerationRevision:number;expectedAiTextEditRevision:number}|{contractVersion:'class-review-generation-command-v1';intent:'discard_candidate';generationId:string;expectedGenerationRevision:number}
export interface GenerationStatusBaseV1{contractVersion:'class-review-generation-status-v1';generationId:string;generationRevision:number;includedEssayCount:number;issueEligibleEssayCount:number;totalEssayCount:number;createdAt:string}
export type ClassReviewGenerationStatusV1=(GenerationStatusBaseV1&{state:'queued'|'running'})|(GenerationStatusBaseV1&{state:'result_unknown';safeFailureCode:'provider_result_unknown'})|(GenerationStatusBaseV1&{state:'succeeded';semanticCoverage:SemanticCoverageV1;completedAt:string})|(GenerationStatusBaseV1&{state:'succeeded_unapplied';semanticCoverage:SemanticCoverageV1;safeUnappliedReason:SafeUnappliedReason;completedAt:string})|(GenerationStatusBaseV1&{state:'failed';safeFailureCode:SafeFailureCode;completedAt:string})|(GenerationStatusBaseV1&{state:'discarded';completedAt:string})|(GenerationStatusBaseV1&{state:'invalidated';safeFailureCode:'class_review_source_invalidated'|'class_review_task_invalidated';completedAt:string})
export type ActionableGenerationSummaryV1={generationId:string;generationRevision:number;state:'queued'|'running';createdAt:string}|{generationId:string;generationRevision:number;state:'result_unknown';safeFailureCode:'provider_result_unknown';createdAt:string}|{generationId:string;generationRevision:number;state:'succeeded_unapplied';safeUnappliedReason:SafeUnappliedReason;createdAt:string;completedAt:string}
export interface ReportCommonV1{contractVersion:'class-review-report-v1';taskRevision:number;reportRevision:number|null;aiTextEditRevision:number;currentGeneration:ActionableGenerationSummaryV1|null;statistics:ClassReviewStatisticsV1;issueBlocks:never[];issueOrder:never[];clearSpellingItems:never[];selectedMaterials:never[]}
export type ClassReviewReportV1=(ReportCommonV1&{workspaceState:'none';reportRevision:null;aiTextEditRevision:0})|(ReportCommonV1&{workspaceState:'draft'|'ai_removed';reportRevision:number})|(ReportCommonV1&{workspaceState:'ai_available';reportRevision:number;appliedGenerationId:string;generatedAt:string;snapshotMetadata:{includedEssayCount:number;issueEligibleEssayCount:number;totalEssayCount:number;semanticCoverage:SemanticCoverageV1};aiSummary:AiSummaryV1})
export const fail=(code:ParseErrorCode,path:string):ParseResult<never>=>({ok:false,error:{code,path}}); export const pass=<T>(value:T):ParseResult<T>=>({ok:true,value}); export const pointer=(path:string,key:string|number)=>`${path}/${String(key).replaceAll('~','~0').replaceAll('/','~1')}`
export const isRecord=(x:unknown):x is Record<string,unknown>=>typeof x==='object'&&x!==null&&!Array.isArray(x)
export function hasOnlyKeys(x:unknown,path:string,required:string[],optional:string[]=[]):ParseResult<Record<string,unknown>>{if(!isRecord(x))return fail('not_object',path);for(const key of required)if(!(key in x))return fail('missing_key',pointer(path,key));const allowed=new Set([...required,...optional]);const extra=Object.keys(x).filter((key)=>!allowed.has(key)).sort();return extra.length?fail('unknown_key',pointer(path,extra[0])):pass(x)}
function validString(x:string,max:number){let count=0;for(let i=0;i<x.length;i+=1){const u=x.charCodeAt(i);if(u>=0xd800&&u<=0xdbff){const n=x.charCodeAt(i+1);if(n<0xdc00||n>0xdfff)return false;i+=1}else if(u>=0xdc00&&u<=0xdfff)return false;count+=1;if(count>max)return false}return true}
export function stringAt(x:unknown,path:string,max:number,required=true):ParseResult<string>{if(typeof x!=='string')return fail('invalid_type',path);if(!validString(x,max))return fail('limit_exceeded',path);return required&&x.length===0?fail('invalid_value',path):pass(x)}
export function safeIntegerAt(x:unknown,path:string):ParseResult<number>{return typeof x!=='number'?fail('invalid_type',path):!Number.isSafeInteger(x)||x<0?fail('invalid_value',path):pass(x)}
export function finiteAt(x:unknown,path:string,positive=false):ParseResult<number>{return typeof x!=='number'?fail('invalid_type',path):!Number.isFinite(x)||(positive&&x<=0)?fail('invalid_value',path):pass(x)}
export function ratioAt(x:unknown,path:string):ParseResult<number>{const r=finiteAt(x,path);return !r.ok?r:r.value<0||r.value>1?fail('invalid_value',path):r}
export function enumAt<T extends string>(x:unknown,path:string,choices:readonly T[]):ParseResult<T>{if(typeof x!=='string')return fail('invalid_type',path);for(const choice of choices)if(x===choice)return pass(choice);return fail('invalid_value',path)}
export function opaqueAt(x:unknown,path:string):ParseResult<string>{const r=stringAt(x,path,128);return !r.ok?r:/^[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$/.test(r.value)?r:fail('invalid_value',path)}
export function timestampAt(x:unknown,path:string):ParseResult<string>{const r=stringAt(x,path,40);return !r.ok?r:/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(r.value)&&Number.isFinite(Date.parse(r.value))?r:fail('invalid_value',path)}
export function arrayAt<T>(x:unknown,path:string,max:number,parse:(item:unknown,path:string)=>ParseResult<T>):ParseResult<T[]>{if(!Array.isArray(x))return fail('invalid_type',path);if(x.length>max)return fail('limit_exceeded',path);const out:T[]=[];for(let i=0;i<x.length;i+=1){const r=parse(x[i],pointer(path,i));if(!r.ok)return r;out.push(r.value)}return pass(out)}
export function uniqueAt(values:string[],path:string):ParseResult<string[]>{const seen=new Set<string>();for(let i=0;i<values.length;i+=1){if(seen.has(values[i]))return fail('duplicate_value',pointer(path,i));seen.add(values[i])}return pass(values)}
export function parseSemanticCoverage(x:unknown,path:string):ParseResult<SemanticCoverageV1>{const keys=['projectedGroupCount','eligibleGroupCount','groupCoverage','projectedDistinctEssaySupportSum','eligibleDistinctEssaySupportSum','supportWeightedCoverage','projectedOccurrenceSum','eligibleOccurrenceSum','occurrenceWeightedCoverage'];const r=hasOnlyKeys(x,path,keys);if(!r.ok)return r;const a=safeIntegerAt(r.value.projectedGroupCount,pointer(path,'projectedGroupCount'));if(!a.ok)return a;const b=safeIntegerAt(r.value.eligibleGroupCount,pointer(path,'eligibleGroupCount'));if(!b.ok)return b;const c=ratioAt(r.value.groupCoverage,pointer(path,'groupCoverage'));if(!c.ok)return c;const d=safeIntegerAt(r.value.projectedDistinctEssaySupportSum,pointer(path,'projectedDistinctEssaySupportSum'));if(!d.ok)return d;const e=safeIntegerAt(r.value.eligibleDistinctEssaySupportSum,pointer(path,'eligibleDistinctEssaySupportSum'));if(!e.ok)return e;const f=ratioAt(r.value.supportWeightedCoverage,pointer(path,'supportWeightedCoverage'));if(!f.ok)return f;const g=safeIntegerAt(r.value.projectedOccurrenceSum,pointer(path,'projectedOccurrenceSum'));if(!g.ok)return g;const h=safeIntegerAt(r.value.eligibleOccurrenceSum,pointer(path,'eligibleOccurrenceSum'));if(!h.ok)return h;const i=ratioAt(r.value.occurrenceWeightedCoverage,pointer(path,'occurrenceWeightedCoverage'));if(!i.ok)return i;if(b.value>a.value||e.value>d.value||h.value>g.value||(a.value===0&&c.value!==1)||(a.value>0&&Math.abs(c.value-b.value/a.value)>1e-12)||(d.value===0&&f.value!==1)||(d.value>0&&Math.abs(f.value-e.value/d.value)>1e-12)||(g.value===0&&i.value!==1)||(g.value>0&&Math.abs(i.value-h.value/g.value)>1e-12))return fail('invalid_value',path);return pass({projectedGroupCount:a.value,eligibleGroupCount:b.value,groupCoverage:c.value,projectedDistinctEssaySupportSum:d.value,eligibleDistinctEssaySupportSum:e.value,supportWeightedCoverage:f.value,projectedOccurrenceSum:g.value,eligibleOccurrenceSum:h.value,occurrenceWeightedCoverage:i.value})}
