import type { GradingResult } from '../../types'
import type { AiGradingResultV1, MultimodalGradingRequestV2 } from './types'

export function adaptAiGradingResult(
  result: AiGradingResultV1,
  _request: MultimodalGradingRequestV2,
): GradingResult {
  return {
    id: `${result.essayId}-result`,
    essayId: result.essayId,
    resultVersion: result.resultVersion,
    source: result.provider,
    reviewReasons: [...result.reviewReasons],
    transcript: result.transcript,
    recognitionWarnings: [...result.recognitionWarnings],
    printedTextExcluded: result.printedTextExcluded,
    totalScore: result.totalScore,
    dimensionScores: result.dimensionScores.map((dimension) => ({
      id: dimension.dimensionId,
      name: dimension.name,
      score: dimension.score,
      maxScore: dimension.maxScore,
      weight: dimension.weight,
      reason: dimension.reason,
      evidence: dimension.evidence,
      needsTeacherReview: dimension.requiresTeacherReview,
    })),
    errorAnnotations: result.issues.map((issue) => ({
      id: issue.id,
      type: issue.type,
      original: issue.originalText,
      suggestion: issue.suggestion,
      explanation: issue.explanation,
      severity: issue.severity,
      evidenceCertainty: issue.evidenceCertainty,
      needsTeacherReview: issue.requiresTeacherReview,
    })),
    sentenceRevisions: result.sentenceRevisions.map((revision) => ({
      id: revision.id,
      relatedErrorIds: [...revision.relatedIssueIds],
      original: revision.originalText,
      revised: revision.revisedText,
      note: revision.note,
      changeTypes: [...revision.changeTypes],
      needsTeacherReview: revision.requiresTeacherReview,
    })),
    upgradedExpressions: result.expressionUpgrades.map((upgrade) => ({
      id: upgrade.id,
      original: upgrade.originalText,
      upgraded: upgrade.upgradedText,
      note: upgrade.note,
      needsTeacherReview: upgrade.requiresTeacherReview,
    })),
    fullTextRevision: result.fullTextRevision
      ? {
          originalText: result.fullTextRevision.originalText,
          correctedText: result.fullTextRevision.correctedText,
          polishedText: result.fullTextRevision.improvedText,
          sentencePairs: result.fullTextRevision.sentencePairs.map((pair) => ({
            id: pair.id,
            original: pair.originalText,
            corrected: pair.correctedText,
            polished: pair.improvedText,
            relatedErrorIds: [...pair.relatedIssueIds],
            changeTypes: [...pair.changeTypes],
            explanation: pair.explanation,
            needsTeacherReview: pair.requiresTeacherReview,
          })),
          logicIssues: result.fullTextRevision.logicIssues.map((issue) => ({
            id: issue.id,
            original: issue.originalText,
            contextBefore: issue.contextBefore,
            contextAfter: issue.contextAfter,
            subType: issue.subType,
            severity: issue.severity,
            diagnosis: issue.diagnosis,
            suggestedAction: issue.suggestedAction,
            conservativeSuggestion: issue.conservativeSuggestion,
            polishedSuggestion: issue.polishedSuggestion,
            needsTeacherReview: issue.requiresTeacherReview,
          })),
          logicNotes: [...result.fullTextRevision.logicNotes],
        }
      : undefined,
    overallComment: result.overallComment,
    legibilityIssues: result.legibilityIssues.map((issue) => ({ ...issue, possibleReadings: [...issue.possibleReadings] })),
    teacherAdjusted: false,
    createdAt: result.createdAt,
    updatedAt: result.createdAt,
  }
}
