import type { FullTextChangeType } from '../../types/index.js'
import { hasDistinctNormalizedText } from './gradingResultSemantics.js'
import { calculateDimensionMaxScore, calculateTotalScore, capTotalScoreForVisibleLegibilityDeduction, hasValidRubricWeights } from './scoringRules.js'
import { validateGradingResultSemantics } from './validateGradingResultSemantics.js'
import type { AiGradingResultV1, ConfirmedTaskPackageV2, GradingClientResponse, GradingErrorCode, GradingFailureV1 } from './types.js'

export interface ExpectedGradingResponse { httpOk: boolean; requestId: string; essayId: string; requireMultimodal?: boolean; inputMode?: 'images' | 'confirmed_text'; confirmedTranscript?: string; pageCount?: number; fullScore?: number; task?: ConfirmedTaskPackageV2 }
const safeMessages: Record<GradingErrorCode, string> = { invalid_request: '批改请求无效。', confirmed_transcript_required: '请先确认作文文本。', unsupported_genre: '当前任务类型暂不支持。', provider_not_configured: '批改服务尚未配置。', provider_request_rejected: '批改请求未被服务接受。', provider_auth_failed: '批改服务认证失败。', provider_balance_unavailable: '批改服务额度暂不可用。', provider_rate_limited: '批改服务繁忙，请稍后重试。', provider_timeout: '批改服务响应超时，请重试。', provider_unavailable: '批改服务暂时不可用，请重试。', provider_content_filtered: '内容暂时无法处理。', provider_unexpected_tool_call: '批改服务返回了无法使用的结果。', provider_invalid_response: '批改服务返回了无法使用的结果。', request_too_large: '上传内容超过允许限制。', gateway_invalid_response: '批改服务返回了无法安全使用的响应，请重试或使用 mock 回退。', gateway_unavailable: '批改服务暂时不可用，请重试或使用 mock 回退。' }
const providers = new Set(['mock', 'remote']), successStatuses = new Set(['success', 'partial']), issueTypes = new Set(['grammar', 'spelling', 'word_choice', 'structure']), severities = new Set(['low', 'medium', 'high']), evidenceCertainties = new Set(['certain', 'uncertain'])
const logicSubTypes = new Set(['weak_connection', 'unclear_logic', 'missing_cause_effect', 'unclear_transition', 'topic_drift', 'irrelevant_sentence', 'unclear_reference', 'missing_motivation', 'plot_gap']), logicSuggestedActions = new Set(['add_connector', 'add_bridge_sentence', 'delete_sentence', 'replace_sentence', 'clarify_reference', 'ask_student_to_explain'])
const changeTypes = new Set<FullTextChangeType>(['grammar', 'spelling', 'word_choice', 'sentence_upgrade', 'coherence', 'logic_bridge', 'delete_suggestion', 'replace_sentence', 'reference_clarification']), errorCodes = new Set<GradingErrorCode>(Object.keys(safeMessages) as GradingErrorCode[])
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function hasExactKeys(value: Record<string, unknown>, required: string[], optional: string[] = []) { const keys = Object.keys(value); return required.every((key) => key in value) && keys.every((key) => required.includes(key) || optional.includes(key)) }
function readString(value: unknown, maxLength = 50_000) { return typeof value === 'string' && value.trim().length > 0 && value.length <= maxLength ? value : null }
function readFiniteNumber(value: unknown) { return typeof value === 'number' && Number.isFinite(value) ? value : null }
function readBoolean(value: unknown) { return typeof value === 'boolean' ? value : null }
function readStringArray(value: unknown, maxItems = 100, maxLength = 10_000, minItems = 0) { if (!Array.isArray(value) || value.length < minItems || value.length > maxItems) return null; const result = value.map((item) => readString(item, maxLength)); return result.every((item): item is string => item !== null) ? result : null }
function projectArray<T>(value: unknown, projector: (item: unknown) => T | null, maxItems = 100): T[] | null { if (!Array.isArray(value) || value.length > maxItems) return null; const result = value.map(projector); return result.every((item): item is T => item !== null) ? result : null }
function hasUniqueIds<T extends { id: string }>(items: T[]) { return new Set(items.map(({ id }) => id)).size === items.length }
function projectChangeTypes(value: unknown): FullTextChangeType[] | null { const result = readStringArray(value, 20, 64, 1); return result && new Set(result).size === result.length && result.every((item) => changeTypes.has(item as FullTextChangeType)) ? result as FullTextChangeType[] : null }
function projectRelatedIssueIds(value: unknown) { const result = readStringArray(value, 100, 200); return result && new Set(result).size === result.length ? result : null }
function projectDimensionScore(value: unknown): AiGradingResultV1['dimensionScores'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['dimensionId', 'name', 'score', 'maxScore', 'weight', 'reason', 'evidence'], ['requiresTeacherReview'])) return null; const dimensionId = readString(value.dimensionId, 200), name = readString(value.name, 200), score = readFiniteNumber(value.score), maxScore = readFiniteNumber(value.maxScore), weight = readFiniteNumber(value.weight), reason = readString(value.reason), evidence = readString(value.evidence); if (!dimensionId || !name || score === null || maxScore === null || weight === null || score < 0 || maxScore < 0 || score > maxScore || weight <= 0 || weight > 100 || !reason || !evidence || ('requiresTeacherReview' in value && typeof value.requiresTeacherReview !== 'boolean')) return null; return { dimensionId, name, score, maxScore, weight, reason, evidence, ...('requiresTeacherReview' in value ? { requiresTeacherReview: value.requiresTeacherReview as boolean } : {}) } }
function projectIssue(value: unknown): AiGradingResultV1['issues'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'type', 'severity', 'originalText', 'suggestion', 'explanation', 'evidenceCertainty', 'requiresTeacherReview'])) return null; const id = readString(value.id, 200), type = readString(value.type, 32), severity = readString(value.severity, 16), originalText = readString(value.originalText), suggestion = readString(value.suggestion), explanation = readString(value.explanation), evidenceCertainty = readString(value.evidenceCertainty, 16), requiresTeacherReview = readBoolean(value.requiresTeacherReview); return id && type && issueTypes.has(type) && severity && severities.has(severity) && originalText && suggestion && explanation && evidenceCertainty && evidenceCertainties.has(evidenceCertainty) && requiresTeacherReview !== null ? { id, type: type as AiGradingResultV1['issues'][number]['type'], severity: severity as AiGradingResultV1['issues'][number]['severity'], originalText, suggestion, explanation, evidenceCertainty: evidenceCertainty as AiGradingResultV1['issues'][number]['evidenceCertainty'], requiresTeacherReview } : null }
function projectSentenceRevision(value: unknown): AiGradingResultV1['sentenceRevisions'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'relatedIssueIds', 'originalText', 'revisedText', 'note', 'changeTypes'], ['requiresTeacherReview'])) return null; const id = readString(value.id, 200), relatedIssueIds = projectRelatedIssueIds(value.relatedIssueIds), originalText = readString(value.originalText), revisedText = readString(value.revisedText), note = readString(value.note), changeTypes = projectChangeTypes(value.changeTypes); if (!id || !relatedIssueIds || !originalText || !revisedText || !note || !changeTypes || ('requiresTeacherReview' in value && typeof value.requiresTeacherReview !== 'boolean')) return null; return { id, relatedIssueIds, originalText, revisedText, note, changeTypes, ...('requiresTeacherReview' in value ? { requiresTeacherReview: value.requiresTeacherReview as boolean } : {}) } }
function projectExpressionUpgrade(value: unknown): AiGradingResultV1['expressionUpgrades'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'originalText', 'upgradedText', 'note'], ['requiresTeacherReview'])) return null; const id = readString(value.id, 200), originalText = readString(value.originalText), upgradedText = readString(value.upgradedText), note = readString(value.note); return id && originalText && upgradedText && note && (!('requiresTeacherReview' in value) || typeof value.requiresTeacherReview === 'boolean') ? { id, originalText, upgradedText, note, ...('requiresTeacherReview' in value ? { requiresTeacherReview: value.requiresTeacherReview as boolean } : {}) } : null }
function projectSentencePair(value: unknown): NonNullable<AiGradingResultV1['fullTextRevision']>['sentencePairs'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'originalText', 'correctedText', 'improvedText', 'relatedIssueIds', 'changeTypes', 'explanation', 'requiresTeacherReview'])) return null; const id = readString(value.id, 200), originalText = readString(value.originalText), correctedText = readString(value.correctedText), improvedText = readString(value.improvedText), relatedIssueIds = projectRelatedIssueIds(value.relatedIssueIds), changeTypes = projectChangeTypes(value.changeTypes), explanation = readString(value.explanation), requiresTeacherReview = readBoolean(value.requiresTeacherReview); return id && originalText && correctedText && improvedText && relatedIssueIds && changeTypes && explanation && requiresTeacherReview !== null ? { id, originalText, correctedText, improvedText, relatedIssueIds, changeTypes, explanation, requiresTeacherReview } : null }
function projectLogicIssue(value: unknown): NonNullable<NonNullable<AiGradingResultV1['fullTextRevision']>['logicIssues']>[number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'originalText', 'contextBefore', 'contextAfter', 'subType', 'severity', 'diagnosis', 'suggestedAction', 'conservativeSuggestion', 'polishedSuggestion', 'requiresTeacherReview'])) return null; const id = readString(value.id, 200), originalText = readString(value.originalText), contextBefore = typeof value.contextBefore === 'string' && value.contextBefore.length <= 50_000 ? value.contextBefore : null, contextAfter = typeof value.contextAfter === 'string' && value.contextAfter.length <= 50_000 ? value.contextAfter : null, subType = readString(value.subType, 64), severity = readString(value.severity, 16), diagnosis = readString(value.diagnosis), suggestedAction = readString(value.suggestedAction, 64), conservativeSuggestion = readString(value.conservativeSuggestion), polishedSuggestion = readString(value.polishedSuggestion), requiresTeacherReview = readBoolean(value.requiresTeacherReview); return id && originalText && contextBefore !== null && contextAfter !== null && subType && logicSubTypes.has(subType) && severity && severities.has(severity) && diagnosis && suggestedAction && logicSuggestedActions.has(suggestedAction) && conservativeSuggestion && polishedSuggestion && requiresTeacherReview !== null ? { id, originalText, contextBefore, contextAfter, subType: subType as NonNullable<NonNullable<AiGradingResultV1['fullTextRevision']>['logicIssues']>[number]['subType'], severity: severity as NonNullable<NonNullable<AiGradingResultV1['fullTextRevision']>['logicIssues']>[number]['severity'], diagnosis, suggestedAction: suggestedAction as NonNullable<NonNullable<AiGradingResultV1['fullTextRevision']>['logicIssues']>[number]['suggestedAction'], conservativeSuggestion, polishedSuggestion, requiresTeacherReview } : null }
function projectLegibilityIssue(value: unknown): AiGradingResultV1['legibilityIssues'][number] | null { if (!isRecord(value) || !hasExactKeys(value, ['id', 'transcriptText', 'possibleReadings', 'pageNumber', 'regionDescription', 'explanation', 'defaultOutcome'])) return null; const id = readString(value.id, 200), transcriptText = readString(value.transcriptText), possibleReadings = readStringArray(value.possibleReadings, 4, 1_000, 2), regionDescription = readString(value.regionDescription), explanation = readString(value.explanation); return id && transcriptText && possibleReadings && hasDistinctNormalizedText(possibleReadings) && Number.isInteger(value.pageNumber) && (value.pageNumber as number) >= 1 && regionDescription && explanation && value.defaultOutcome === 'count_as_legibility_error' ? { id, transcriptText, possibleReadings, pageNumber: value.pageNumber as number, regionDescription, explanation, defaultOutcome: 'count_as_legibility_error' } : null }
function projectFullTextRevision(value: unknown): NonNullable<AiGradingResultV1['fullTextRevision']> | null { if (!isRecord(value) || !hasExactKeys(value, ['originalText', 'correctedText', 'improvedText', 'sentencePairs', 'logicNotes', 'logicIssues'])) return null; const originalText = readString(value.originalText), correctedText = readString(value.correctedText), improvedText = readString(value.improvedText), sentencePairs = projectArray(value.sentencePairs, projectSentencePair, 100), logicNotes = readStringArray(value.logicNotes, 100, 50_000), logicIssues = projectArray(value.logicIssues, projectLogicIssue, 50); return originalText && correctedText && improvedText && sentencePairs && logicNotes && logicIssues ? { originalText, correctedText, improvedText, sentencePairs, logicNotes, logicIssues } : null }
function projectSuccess(value: unknown, expected: ExpectedGradingResponse): AiGradingResultV1 | null {
  if (!isRecord(value) || !hasExactKeys(value, ['resultVersion', 'requestId', 'essayId', 'provider', 'status', 'totalScore', 'maxScore', 'dimensionScores', 'issues', 'sentenceRevisions', 'expressionUpgrades', 'fullTextRevision', 'recognitionWarnings', 'legibilityIssues', 'overallComment', 'reviewReasons', 'createdAt'], ['modelSelfConfidence', 'transcript', 'printedTextExcluded'])) return null
  const requestId = readString(value.requestId, 200), essayId = readString(value.essayId, 200), provider = readString(value.provider, 32), status = readString(value.status, 16), totalScore = readFiniteNumber(value.totalScore), maxScore = readFiniteNumber(value.maxScore), dimensionScores = projectArray(value.dimensionScores, projectDimensionScore, 10), issues = projectArray(value.issues, projectIssue, 100), sentenceRevisions = projectArray(value.sentenceRevisions, projectSentenceRevision, 100), expressionUpgrades = projectArray(value.expressionUpgrades, projectExpressionUpgrade, 100), recognitionWarnings = readStringArray(value.recognitionWarnings, 50, 1_000), legibilityIssues = projectArray(value.legibilityIssues, projectLegibilityIssue, 50), overallComment = readString(value.overallComment, 50_000), reviewReasons = readStringArray(value.reviewReasons, 100, 50_000), createdAt = readString(value.createdAt, 100)
  if (value.resultVersion !== 'grading-result-v2' || requestId !== expected.requestId || essayId !== expected.essayId || !provider || !providers.has(provider) || !status || !successStatuses.has(status) || totalScore === null || maxScore === null || totalScore < 0 || maxScore < 0 || totalScore > maxScore || !dimensionScores || !issues || !sentenceRevisions || !expressionUpgrades || !recognitionWarnings || !legibilityIssues || !overallComment || !reviewReasons || !createdAt || !Number.isFinite(Date.parse(createdAt))) return null
  const roundedTotalScore = calculateTotalScore(dimensionScores.map(({ score }) => score), maxScore)
  const legibilityDimension = dimensionScores.find(({ dimensionId }) => dimensionId === 'legibility')
  const expectedTotalScore = legibilityDimension
    ? capTotalScoreForVisibleLegibilityDeduction(roundedTotalScore, maxScore, legibilityDimension.score, legibilityDimension.maxScore, legibilityIssues.length > 0)
    : roundedTotalScore
  if (!hasValidRubricWeights(dimensionScores.map(({ weight }) => weight)) || (expected.fullScore !== undefined && maxScore !== expected.fullScore) || dimensionScores.some((item) => item.maxScore !== calculateDimensionMaxScore(maxScore, item.weight)) || expectedTotalScore !== totalScore) return null
  const issueIds = new Set(issues.map(({ id }) => id))
  if (issueIds.size !== issues.length || !hasUniqueIds(sentenceRevisions) || !hasUniqueIds(expressionUpgrades) || !hasUniqueIds(legibilityIssues) || new Set(dimensionScores.map(({ dimensionId }) => dimensionId)).size !== dimensionScores.length) return null
  const fullTextRevision = projectFullTextRevision(value.fullTextRevision); if (!fullTextRevision || !hasUniqueIds(fullTextRevision.sentencePairs) || !hasUniqueIds(fullTextRevision.logicIssues)) return null
  const unifiedIssueIds = new Set([...issueIds, ...fullTextRevision.logicIssues.map(({ id }) => id)])
  if (unifiedIssueIds.size !== issues.length + fullTextRevision.logicIssues.length || [...sentenceRevisions, ...fullTextRevision.sentencePairs].some(({ relatedIssueIds }) => relatedIssueIds.some((id) => !unifiedIssueIds.has(id)))) return null
  let modelSelfConfidence: number | undefined; if ('modelSelfConfidence' in value) { modelSelfConfidence = readFiniteNumber(value.modelSelfConfidence) ?? undefined; if (modelSelfConfidence === undefined || modelSelfConfidence < 0 || modelSelfConfidence > 1) return null }
  const hasMultimodalFields = expected.requireMultimodal || 'transcript' in value || 'printedTextExcluded' in value; let transcript: string | undefined, printedTextExcluded: boolean | undefined
  if (hasMultimodalFields) { transcript = readString(value.transcript, 50_000) ?? undefined; printedTextExcluded = readBoolean(value.printedTextExcluded) ?? undefined; if (!transcript || printedTextExcluded === undefined || fullTextRevision.originalText !== transcript) return null }
  if (expected.inputMode === 'confirmed_text' && (transcript !== expected.confirmedTranscript || recognitionWarnings.length > 0 || legibilityIssues.length > 0 || printedTextExcluded !== true)) return null
  if (expected.inputMode === 'images' && (!Number.isInteger(expected.pageCount) || expected.pageCount! < 1 || legibilityIssues.some(({ pageNumber }) => pageNumber > expected.pageCount!))) return null
  const result: AiGradingResultV1 = { resultVersion: 'grading-result-v2', requestId, essayId, provider: provider as AiGradingResultV1['provider'], status: status as AiGradingResultV1['status'], totalScore, maxScore, dimensionScores, issues, sentenceRevisions, expressionUpgrades, recognitionWarnings, legibilityIssues, fullTextRevision, overallComment, ...(modelSelfConfidence === undefined ? {} : { modelSelfConfidence }), ...(transcript === undefined ? {} : { transcript, printedTextExcluded }), reviewReasons, createdAt }
  if (expected.requireMultimodal) {
    if (!expected.task || !expected.inputMode || expected.pageCount === undefined) return null
    if (!validateGradingResultSemantics(result, {
      task: expected.task,
      inputMode: expected.inputMode,
      pageCount: expected.pageCount,
      ...(expected.confirmedTranscript === undefined ? {} : { confirmedTranscript: expected.confirmedTranscript }),
    })) return null
  }
  return result
}
function projectFailure(value: unknown, expected: ExpectedGradingResponse): GradingFailureV1 | null { if (!isRecord(value) || !hasExactKeys(value, ['requestId', 'status', 'error']) || !isRecord(value.error) || !hasExactKeys(value.error, ['code', 'message', 'retryable'])) return null; const requestId = readString(value.requestId, 200), code = readString(value.error.code, 64), message = readString(value.error.message), retryable = readBoolean(value.error.retryable); return requestId === expected.requestId && value.status === 'failed' && code && errorCodes.has(code as GradingErrorCode) && message && retryable !== null ? { requestId, status: 'failed', error: { code: code as GradingErrorCode, message: safeMessages[code as GradingErrorCode], retryable } } : null }
export function gatewayInvalidResponse(requestId: string): GradingFailureV1 { return { requestId, status: 'failed', error: { code: 'gateway_invalid_response', message: safeMessages.gateway_invalid_response, retryable: true } } }
export function projectGradingClientResponse(value: unknown, expected: ExpectedGradingResponse): GradingClientResponse { return (expected.httpOk ? projectSuccess(value, expected) : projectFailure(value, expected)) ?? gatewayInvalidResponse(expected.requestId) }
